server:
  port: 80
  servlet:
    context-path: /api
cors:
  urls: *
logging:
  level:
    org.togglz: DEBUG
togglz:
  feature-enums: com.example.demo.TodoFeatures
  console:
    enabled: true
    secured: false
    path: /
    use-management-port: false
spring:
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
  thymeleaf:
    enabled: true
  h2:
    console:
      enabled: true
  application:
    admin:
      enabled: true
  security:
    user.name: admin
    user.password: test
    user.roles: ADMIN