server:
  port: 8080
#  servlet:
#    context-path: /api
logging:
  level:
    org.togglz: DEBUG
togglz:
  features:
    BOOK_WISHLIST:
      enabled: true
  feature-enums: com.example.demo.TodoFeatures
  console:
    enabled: true
    secured: false
    path: /togglz-console
    use-management-port: false
spring:
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
  thymeleaf:
    enabled=true:
  h2:
    console:
      enable: true
  application:
    admin:
      enabled: true
  security:
    user.name: admin
    user.password: test
    user.roles: ADMIN